### ISSUE TITLE
Show MailChimp Form Metabox context should be "side"

### ISSUE THREAD

**Issue by d4mation** [dragonslayerindustries/learndash-mailchimp#41]
The size of this metabox is very large for a single checkbox input.

https://developer.wordpress.org/reference/functions/add_meta_box/

![image](https://user-images.githubusercontent.com/7770631/29775989-35ec304a-8bd5-11e7-95f2-193070840d50.png)

Also, the styling/positioning of the checkbox is odd. It should probably more closely match default WordPress styles.

Discussion Metabox for reference:
![image](https://user-images.githubusercontent.com/7770631/29776056-6a02a1ca-8bd5-11e7-854b-02bfae7543a0.png)

**Comment by objectsweb** [comment]
- Some enhancements done, Check please.

**Comment by d4mation** [comment]
Could you try setting the Context for this Metabox to `side`? For a single checkbox, it seems to be a bit of a waste to have such a large Metabox.

**Comment by objectsweb** [comment]
Done, Kindly check.

**Comment by brashrebel** [comment]
This does not appear to be done. The metabox still appears in the main column and not on the side. Also, "subscription" is spelled incorrectly in "Show Subscribtion Form".

**Comment by objectsweb** [comment]
please check again

**Comment by d4mation** [comment]
This should be set with one minor change. The `low` Priority parameter is unnecessary and causes it to load all the way at the bottom of the page below "Featured Image".

If the parameter is removed (Allowing it to default to `default`), it loads just above "Featured Image". If you use `low` and they have lots of other plugins enabled, it could hide that option incredibly far down the page.

**Comment by objectsweb** [comment]
ok done

**Comment by brashrebel** [comment]
Perfect!
